# -*- coding: utf-8 -*-
"""Automate EDA day-04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nyrSQ4S2vKDOCMFOAnEwyXFNjDpfU-lA
"""

! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport



import seaborn as sns

# import dataset from seaborn

df = sns.load_dataset('tips')
df.head()

profile = ProfileReport(df, title='tips', html={'style':{'full_width':True}})

profile.to_file('output.html')

#dtale

!pip install dtale

import seaborn as sns
import pandas as pd
df1 = sns.load_dataset('titanic')

df1.head()

import dtale
dtale.show(df)

pip install dtale

import dtale
import pandas as pd

df = pd.DataFrame([dict(a=1,b=2,c=3)])

# Assigning a reference to a running D-Tale process
d = dtale.show(df)

import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

df.head()

from

import dtale

import Loader

import dtale
dtale.cli.loaders.arctic_loader.find_loader(df)

import dtale
import pandas as pd

df = pd.DataFrame([dict(a=1,b=2,c=3)])

# Assigning a reference to a running D-Tale process
d = dtale.show(df)

# Accessing data associated with D-Tale process
tmp = d.data.copy()
tmp['d'] = 4

# Altering data associated with D-Tale process
# FYI: this will clear any front-end settings you have at the time for this process (filter, sorts, formatting)
d.data = tmp

# Shutting down D-Tale process
d.kill()

# using Python's `webbrowser` package it will try and open your server's default browser to this process
d.open_browser()

# There is also some helpful metadata about the process
d._data_id  # the process's data identifier
d._url  # the url to access the process

d2 = dtale.get_instance(d._data_id)  # returns a new reference to the instance running at that data_id

dtale.instances()  # prints a list of all ids & urls of running D-Tale sessions

pip install dtale

import dtale

import dtale

pip install dtale

import dtale

import pandas as pd

import seaborn as sns

df = sns.load_dataset('titanic')
df.head()

import dtale
dtale.show(df)

pip install sweetviz

import sweetviz as sv

report = sv.analyze(df)
report.show_html('new.html')

!pip install dataprep

from dataprep.eda import create_report
create_report(df)

import pandas as pd

import seaborn as sns

df = sns.load_dataset('titanic')
df.head()

pip install autoviz

from autoviz.AutoViz_Class import AutoViz_Class

AutoViz_Class(df)

from autoviz.AutoViz_Class import AutoViz_Class

AutoViz_Class(df)

pip install lux

import lux
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df

df.intent = ["AverageCost","SATAverage"]
df

